apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: backend-app
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-app
        tier: backend
        track: stable
    spec:
      containers:
        - name: backend-app
          image: {{ .Values.image }}
          ports:
            - name: http
              containerPort: 4000
